# Plugins
plugins:
- jekyll-sitemap
safe: false

# Sass Settings
sass:
  sass_dir: _sass
  style: compressed

# Build Settings
markdown: kramdown
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'blog.html', 'hackathon.html', '_posts', 'cod.md']

# Site Settings
title: "Craft-IT | Konferencja programistyczna w Rzeszowie"
email: ""
description: "Konferencja programistyczna w Rzeszowie powicona tematyce Software Craftsmanship - dobrym praktykom i metodykom, nie zwizanymi cile z konkretnymi technologiami."
baseurl: ""
url: "http://craft-it.pl"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "G-22X49QWFY7"
googleAnalyticsSiteUrl: "auto"
siteVerification: "4-JP2CVATViH_jUFGK_qzECdxzEKOzBRlzlRQMIzQVc"

# Organizer Info
organizerName: ""
organizerAlternateName: ""
organizerDescription: ""
organizerEmail: ""
organizerLogo: ""
organizerLink: ""

# Head
metaKeywords: "Craft-IT, RZEmiosloIT, Rzesz贸w, konferencja, programowanie, software, craftsmanship, IT"
twitterAccount: "@RZEmiosloIT"
socialImageSrcTwitter: "/img/seo/craft-it-2023-sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/craft-it-2023-sharing-fb.png"

# Documents
#c4pUrl: ""
#c4sponsorsUrl: ""

# Navigation
navigationLinks:
# - {permalink: "/#schedule", text: "Program"}
# - {permalink: "/speakers/", text: "Prelegenci"}
#- {permalink: "/team/", text: "Zesp贸"}
#- {permalink: "/logistics/", text: "Logistyka"}
- {permalink: "/#past-speakers", text: "Prelegenci"}
- {permalink: "/#last-editions2", text: "Relacja"}
- {permalink: "/#location-map", text: "Lokalizacja"}
navigationButtons:
 - {permalink: "/#tickets", text: "Kup bilet"}
bottomNavigationLinks:
 - {permalink: "/#tickets", text: "Kup bilet"}
#rightNavigationButtons:
# - {link: "#tickets", text: "Kup bilet"}

# Hero Block
heroImage: "hero.png"
#heroButtons:
# - {link: "", text: "Zosta prelegentem"}
# - {permalink: "/#tickets", text: "Kup bilet"}

# About Block
aboutTitle: "O konferencji"
aboutText:
 - "Craft-IT.pl to konferencja programistyczna na Podkarpaciu powicona tematyce <i>Software Craftsmanship</i>."
 - "Nowe technologie pojawiaj si i znikaj. My wierzymy, 偶e warto inwestowa we wasne programistyczne rzemioso, w warsztat, kt贸ry zawsze bdzie aktualny, niezale偶nie od aktualnych trend贸w."
 - "Zapewniamy wietne prelekcje techniczne, catering przez cay dzie i after party."
#aboutBlock:
# - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
# - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
# - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 20
rockstarSpeakersTitle: "Prelegenci"
rockstarSpeakersButtonText: "Wicej szczeg贸贸w"

# Latest News Block
latestNewsTitle: "Aktualnoci"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: ""
twitterHashTag: "RZEmiosloIT"
twitterFeed: ""

# Location Block
locationBlockTitle: "Lokalizacja"
eventLocationName: "??"
eventLocationLink: "??"
#eventStreetAddress: "Al. Wacawa Kopisto 1"
eventAddressLocality: "Rzesz贸w"
eventAddressLocalityRegion: "Rzesz贸w"
#eventPostalCode: "35-315"
#eventAddressCountry: "Polska"
#eventStartTime: "2019-05-25T09:00"
#eventDoorTime: "08:00"
#eventEndTime: "2019-05-26T18:00"
eventPlaceCoordinates: "50.0382509, 22.004591"
mapCenterCoordinates: "50.0382509, 22.004591"
mapMobileCenterCoordinates: "50.0382509, 22.004591"

# Venue Block
venueBlockTitle: "Miejsce"
venueBigImage: "bristol1.jpg"
venueSmallImage1: "bristol-sala1.jpg"
venueSmallImage2: "bristol2.jpg"
venueSmallImage3: "bristol-sala2.jpg"
venueTitle: "Bristol Tradition&Luxury Hotel"
venueSubTitle: ""
venueFeatures: ["Hotel w samym centrum Rzeszowa"]

# Partners Block
organizersTitle: "Organizatorzy"
partnersTitle: "Partnerzy"
partnersC4sponsorsButton: "Zosta sponsorem"

# # Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Rejestracja rozpoczta!"
# subscribeButtons:
  # - {permalink: "/#tickets", text: "Kup bilet"}

# Last edition Block
lastEditionImage: "edition2022.jpg"
lastEditionTitle: "Jak byo w 2024 roku?"
lastEditionButtons:
   - {link: "https://www.facebook.com/media/set/?vanity=craftitpl&set=a.978042694328201", text: "Relacja fotograficzna"}
   - {link: "https://www.youtube.com/watch?v=DxW_78kBVrQ", text: "Relacja wideo"}

# Why Attend Block
whyAttendTitle: "Dlaczego warto?"
whyAttendItems:
  - {emoji: "", title: "Ucz si z&nbsp;dowiadcze", text: "Prawdziwe historie z&nbsp;projekt贸w. Pytania bez cenzury. Czas na&nbsp;dyskusje."}
  - {emoji: "", title: "Buduj network", text: "Poznaj ludzi, kt贸rzy rozwizuj podobne problemy. Buduj sie, od&nbsp;kt贸rej mo偶esz si uczy."}
  - {emoji: "", title: "Dzie na&nbsp;nauk", text: "Pozw贸l sobie na&nbsp;dzie z&nbsp;technologi. Programowanie, bazy danych, metodyki. Bez zooma i&nbsp;slacka."}
  - {emoji: "", title: "Nastpny krok", text: "Konferencja dla developer贸w, tech lead贸w i&nbsp;manager贸w z&nbsp;dowiadczeniem. Tutaj znajdziesz inspiracj do&nbsp;dalszego rozwoju."}

# Video Testimonials Block
videoTestimonialsTitle: "Co m贸wi prelegenci?"
videoTestimonialsSubtitle: "Craft-IT to miejsce dla dowiadczonych in偶ynier贸w, kt贸rzy szukaj inspiracji i konkret贸w. Zobacz, jak wygldaj nasze konferencje z perspektywy prelegent贸w."
# videoTestimonialsYoutubeId: "YOUTUBE_VIDEO_ID"

# Past Speakers Block
pastSpeakersTitle: "Byli u nas"
pastSpeakersSubtitle: "Na naszej scenie wystpili jedni z najlepszych polskich prelegent贸w technicznych."

# Local Speakers Block
localSpeakersTitle: "Lokalne talenty"
localSpeakersSubtitle: "Wspieramy rozw贸j podkarpackiej spoecznoci IT. Konferencja to wsp贸praca dw贸ch meetup贸w: rg-dev i Rzesz贸w Ruby User Group."

# Community Block
communityTitle: "Organizowane przez spoeczno"
communityText: "Craft-IT to konferencja non-profit, organizowana przez Stowarzyszenie CRAFT.IT. Robimy to po godzinach, bo wierzymy, 偶e warto."
communityImage: "placeholder.png"
communityButtonText: "Poznaj zesp贸"

# Tickets Block
ticketsTitle: "Bilety"
ticketsInfo: "Bilety umo偶liwiaj wstp na wszystkie prezentacje, przerwy kawowe, lunch i afterparty. Nocleg nie jest wliczony w cen biletu."
# ticketsInfo: "Informacj o sprzeda偶y bilet贸w podamy na stronie i kanaach social media."

# Footer
socialLinks:
 - {link: "https://twitter.com/craftit_pl", icon: "twitter"}
 - {link: "https://facebook.com/craftitpl/", icon: "facebook"}
 - {link: "https://www.youtube.com/channel/UCKuLHBJ7bMib3JcKN7eP5-Q", icon: "youtube"}
 - {link: "https://www.linkedin.com/company/stowarzyszenie-craft-it/", icon: "linkedin"}
# - {permalink: "/feed.xml", icon: "rss"}
footerInfo:
 -
  title: Stowarzyszenie CRAFT.IT
  data:
   - {text: ""}
footerBlocks:
 - title: "Menu"
   links:
     # - { permalink: "/speakers/", text: "Prelegenci" }
      # - { permalink: "/schedule/", text: "Agenda" }
    - { permalink: "/team/", text: "Zesp贸" }
    - { permalink: "/files/regulamin.pdf", text: "Regulamin" }
    - { permalink: "/files/polityka_prywatnosci.pdf", text: "Polityka Prywatnoci" }
 - title: "Archiwum"
   links:
    - { link: "https://2025.craft-it.pl", text: "2025" }
    - { link: "https://2024.craft-it.pl", text: "2024" }
    - { link: "https://2023.craft-it.pl", text: "2023" }
    - { link: "https://2022.craft-it.pl", text: "2022" }
    - { link: "https://2019.rzemioslo.it", text: "2019" }
    - { link: "https://2018.rzemioslo.it", text: "2018" }
    - { link: "https://2017.rzemioslo.it", text: "2017" }
    - {link: "https://www.facebook.com/media/set/?set=a.1268979385234529&type=3", text: "Relacja fotograficzna"}
    - {link: "https://youtu.be/PqC5TQEZ5UU", text: "Relacja wideo"}
 -
  title: "Social"
  links:
   - {link: "https://twitter.com/craftit_pl", icon: "twitter"}
   - {link: "https://facebook.com/craftitpl/", icon: "facebook"}
   - {link: "https://www.meetup.com/rg-dev/", text: "rg-dev"}
   - {link: "http://rrug.pl/", text: "rrug"}
#-
# title: "Kontakt"
# links:
#  - {link: "mailto:kontakt@rzemioslo.it", text: "kontakt@rzemioslo.it"}

#  - {permalink: "", text: "FAQ"}

# Blog
blogTitle: "Aktualnoci"
blogCommentsEnabled: true
discusShortName: "rzemiosloit"

# Speakers List Block
showSessions: true

# Team Block

# Logistics Find Way Block
# findWayTitle: "Wyznacz tras"
# findWayDistance: "Odlego"
# findWayDriving: "Samoch贸d"
# findWayWalking: "Spacer"
# findWayBicycling: "Rower"
# findWayTransit: "Transport publiczny"
# findWayFindFlight: "Znajd藕 loty"
# logisticsMapCenterCoordinates: "50.082178, 22.003305"
# logisticsMapMobileCenterCoordinates: "50.082178, 22.003305"
# logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsWideCards:
#-
# subCards:
#  -
#   title: "Hotele"
#   links:
#    - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel InTourist", address: "ul. Korfantego 45, 35-225 Rzesz贸w", logoUrl: "hotel_1.gif" }
#    - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel InTourist", address: "ul. Korfantego 45, 35-225 Rzesz贸w", logoUrl: "hotel_1.gif" }
#  -
#   title: "Restauracje"
#   links:
#    - {link: "https://plus.google.com/b/102444623953913144164", text: "Kura Restaurant", address: "ul. Korfantego 45, 35-225 Rzesz贸w", logoUrl: "restaurant_1.jpg" }
